/** Real payer/customer list backing the Payer field's autocomplete —
 *  there's no live payer directory in this app, so this is a static
 *  reference list, not a search against ingested policies. */
export const PAYER_CATALOG: string[] = [
  "Advocate Health Midwest",
  "AlohaCare",
  "Anthem Inc",
  "BCBS NJ",
  "BCBS of AZ",
  "BCBS of MI",
  "BCBS SC",
  "BCBSM Medicare",
  "Blue KC",
  "CareOregon",
  "Cigna Pharmacy Services",
  "Cooperative Benefits Group",
  "Excellus",
  "Gainwell",
  "Geisinger Health Plan",
  "Health Partners",
  "Hometown",
  "Humana",
  "Kaiser Permanente",
  "LucyRx",
  "Maxor National Pharamcy (Maxor)",
  "MC-21",
  "MedOne",
  "Oscar",
  "Pharmacy Benefit Dimensions",
  "Point32Health",
  "ProActRx",
  "Providence Health Plan",
  "RxBenefits",
  "RxResults",
  "Samaritan Health Plans",
  "Sanford Security Health",
  "SelectHealth",
  "Sentara Health Plans",
  "Serve You Custom Rx Mgmnt",
  "SlateRx",
  "Southern Scripts",
  "State of Utah",
  "TrueScripts",
  "Unite Here Health",
  "UPMC Health Plan",
  "US-Rx Care",
  "WellDyneRx",
  "Western Health Advantage",
];
